### ISSUE TITLE
"Client authentication failed due to unknown client" when logging in with Mastodon account (Lite)

### ISSUE THREAD

**Issue by CloakTheLurker** [suvam0451/dhaaga#112]
In Dhaarga Lite (0.6.0), I cannot log in with my usual accounts. I tried with mas.to, mastodon.cloud & mastodon.xyz. I am on a Moto G Play (2021) with Android 11.
![Screenshot_20240804-202313.png](https://github.com/user-attachments/assets/b8e4aaf4-31a8-4952-820f-c82fa71ccb32)

**Comment by suvam0451** [comment]
Ok. It seems a **client_id generated from one instance cannot be used for another instannce.** -> [ref](https://github.com/mastodon/mastodon/issues/20081)

Sine all my accounts are in mastodon.social, other mastodon users are being unable to login.

Will fix by today 🙏

You will get the update at 6pm UTC (when izzy refetches the release).

**Comment by suvam0451** [comment]
The version `v0.6.1` is available in all stores now and should have solved this issue 👍

**Comment by suvam0451** [comment]
Closing this as `v0.7.0` is being released.
