### ISSUE TITLE
False Detection by Windows Defender as of v0.3.0

### ISSUE THREAD

**Issue by suvam0451** [suvam0451/dhaaga#2]
False identification of the installed binary as Trojan.

<p align="center">
  <img width = "320px" height="auto" src="https://github.com/suvam0451/dhaaga/assets/44526763/1422207c-8ae6-46b4-9fe3-0226600d68b5" alt="Sqlite Showcase">
</p>

Root cause unknown. Any help in identifying thus will be much appreciated. ^^

**Comment by salman0ansari** [comment]
You have to sign binary if you want to bypass defender false threat 
use [signtool ](https://learn.microsoft.com/en-us/dotnet/framework/tools/signtool-exe)or [osslsigncode](https://github.com/mtrojnar/osslsigncode)

**Comment by suvam0451** [comment]
Oh, cool. I will try that today.

When I originally looked at the docs for those tools, I felt like they were meant for driver manufacturers. 😄

**Comment by suvam0451** [comment]
I used a self-signed certificate. It fixes the issue for computers in my home network, at least.

I definitely cannot afford an official EV certificate, so will have to be on the lookout for more reports, I guess.
